apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintech-dev
namePrefix: dev-

resources:
  - ../../base

# Reemplazado commonLabels (obsoleto) por labels
labels:
  - pairs:
      environment: development

patches:
  - path: replica-count.yaml
  - path: resources.yaml
  - path: env-config.yaml

configMapGenerator:
  - name: fintech-webapp-config
    # Cambiado de 'merge' a 'create' porque el ConfigMap no existe en los recursos base
    behavior: create
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DISABLE_DB_SYNC=false

images:
  - name: ghcr.io/open-liontechsolution/fintech-personal-web-app
    newName: ghcr.io/open-liontechsolution/fintech-personal-web-app
    newTag: dev-eae2644
