apiVersion: apps/v1
kind: Deployment
metadata:
  name: fintech-webapp
spec:
  template:
    spec:
      containers:
        - name: webapp
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
