{{- if and .Values.frpc.enabled .Values.frpc.sealedsecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frpc-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
    {{- include "fintech-webapp.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- with .Values.frpc.sealedsecrets.encryptedData }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        {{- include "fintech-webapp.selectorLabels" . | nindent 8 }}
      name: frpc-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
