{{- if .Values.sealedsecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.appName }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fintech-webapp.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- with .Values.sealedsecrets.encryptedData }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        {{- include "fintech-webapp.selectorLabels" . | nindent 8 }}
      name: {{ .Values.appName }}-secrets
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
