apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - postgres-ingress-policy.yaml

labels:
- pairs:
    app.kubernetes.io/name: fintech-webapp
    app.kubernetes.io/part-of: fintech-personal
