apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fintech-prod
namePrefix: prod-

resources:
  - ../../base

commonLabels:
  environment: production

patches:
  - path: replica-count.yaml
  - path: resources.yaml
  - path: env-config.yaml

configMapGenerator:
  - name: fintech-webapp-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=warn
      - DISABLE_DB_SYNC=true
